os:
  - linux
  - windows

language: node_js

sudo: false

cache:
  npm: true

node_js:
  - "8"
  - "10"
  - "node"

script:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      git config core.autocrlf false && git add --renormalize . && git reset --hard;
    fi
  - npm run eslint
